Use new main script

diff --git a/termux-env-setup b/termux-env-setup
--- a/termux-env-setup
+++ b/termux-env-setup
@@ -1,38 +1,44 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
-echo ""
-echo "================"
-echo "Update ~/.zshrc:"
-echo "================"
-git -C ~/.termux-bootstrap/ pull
-cp ~/.termux-bootstrap/.zshrc ~/.zshrc
+features=$(find features -maxdepth 1 -type f | sort)
 
-echo ""
-echo "================="
-echo "Install packages:"
-echo "================="
+for feature in $features
+do
+    if [ ! $(stat -c %A $feature | cut -c4) = "x" ]; then
+       echo "$feature is not executable. Aborting."
+       exit 1
+    fi
+done
+
+dialogOptions=$(for x in $features; do
+		    status="on"
+		    installed="X"
+		    if $($x installed); then
+			status="off"
+			installed="(installed)";
+		    fi
+		    echo -n " $x $installed $status"
+		done;)
+
+selectedFeatures=$(dialog \
+		       --output-fd 1 \
+		       --erase-on-exit \
+		       --checklist \
+		       'Select features to install:' \
+		       0 0 0 \
+		       ${dialogOptions[@]})
+
 pkg update
-pkg upgrade -y
-pkg install -y \
-    build-essential \
-    emacs \
-    git \
-    lazygit \
-    man \
-    openssh \
-    termux-api \
-    zsh \
 
-echo ""
-echo "========================"
-echo "Install python packages:"
-echo "========================"
-pkg upgrade -y
-pkg install -y \
-    python \
-    python-numpy \
-    python-scipy \
-    matplotlib
-pip install \
-    lcapy==1.24
+for feature in $selectedFeatures
+do
+    echo ""
+    echo "==========================="
+    echo "Install feature $feature:"
+    echo "==========================="
+    eval "$feature install"
+done
+
+# Switch to zsh
+exec zsh -l
